### ISSUE TITLE
Bug: Incorrect queue elements quantity

### ISSUE THREAD

**Issue by Dzheremi2** [franz-dc/youtube-music-remote#72]
Not all tracks from queue are displayed in the app

<details>
<summary>In-app queue (only 6 tracks)</summary>

![](https://github.com/user-attachments/assets/708fcc34-81d7-47b3-8787-8206ae5627be)

</details>

<details>
<summary>Actual queue (11 tracks)</summary>

![](https://github.com/user-attachments/assets/e553f932-b6c7-45de-9b56-03ff0e8c6782)

</details>

**Comment by franz-dc** [comment]
Sorry, does this happen all the time?
Can you also describe the steps on how did it come up this? I can't seem to reproduce this issue.

**Comment by Dzheremi2** [comment]
> Sorry, does this happen all the time?

When I'm opening my [playlist](https://music.youtube.com/playlist?list=PLsaL1KeATf_YFzqACuBpJCI2Hzsf3IuAO&si=T1XF0fY2lhi4IY1b), it shows only 6 tracks instead of 11
When I'm opening this [album](https://music.youtube.com/playlist?list=OLAK5uy_l6ZpTbjdhYRwxLIuktMljSDv_M7tqkidg&si=x_hOmRTHsHz2uCHh), it shows all tracks except the first one
When I'm opening this [album](https://music.youtube.com/playlist?list=OLAK5uy_n-NAuFSD3ZZ3c6CrKKJRElI8dqRJv65UU&si=9LnMFh5M2I4Op6Eb), it shows only 2 tracks instead of 14

This behavior is incomprehensible. Some playlists and albums shows fully, some only 2 out of 14

> Can you also describe the steps on how did it come up this?
### Reproduction Steps
1. Open app
2. Start new queue on YouTube Music app
3. See queue in Remote Control App is different, than the original one

**Comment by franz-dc** [comment]
Hmm, I still can't reproduce this. Are both YouTube Music and YouTube Music Remote up to date?
On my end, all queue items do render properly.
![image](https://github.com/user-attachments/assets/64cfb655-73d7-455a-9ece-0f7cff968cd0)

**Comment by Dzheremi2** [comment]
May this be caused by that I'm using album song mode, and you're using videos mode?

**Comment by franz-dc** [comment]
From my screenshot, it's actually from the [link](https://music.youtube.com/playlist?list=OLAK5uy_n-NAuFSD3ZZ3c6CrKKJRElI8dqRJv65UU&si=9LnMFh5M2I4Op6Eb) that you've sent.

May I ask if the queue fixes itself if you play another track in the queue or the problem still persist?

**Comment by Dzheremi2** [comment]
> From my screenshot, it's actually from the [link](https://music.youtube.com/playlist?list=OLAK5uy_n-NAuFSD3ZZ3c6CrKKJRElI8dqRJv65UU&si=9LnMFh5M2I4Op6Eb) that you've sent.

When I'm opening that link in the browser, it's loaded in album mode
<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/af7532ab-36ea-41cb-9174-8e79e3254d0c)

</details>

**Comment by franz-dc** [comment]
Maybe a region thing? There are videos on my end when opening that link on the browser.
![image](https://github.com/user-attachments/assets/1d5c4223-7cf0-4598-bec2-8d57241f231c)

**Comment by Dzheremi2** [comment]
I've figured it out, this is because you don't have YT Premium and I do.
YouTube Music shows videos to people without subscription. 

Tested in Incognito without login.

**Comment by Dzheremi2** [comment]
> May I ask if the queue fixes itself if you play another track in the queue or the problem still persist?

Sorry for belated answer. No, it doesn't fix if I play another song

**Comment by franz-dc** [comment]
> I've figured it out, this is because you don't have YT Premium and I do. YouTube Music shows videos to people without subscription.

Ohh, so that explains it.
How about trying an account without YT Premium if that fixes the issue?

**Comment by Dzheremi2** [comment]
> Ohh, so that explains it. How about trying an account without YT Premium if that fixes the issue?

Yes, switching account to the one without subscription solves this Issue

**Comment by franz-dc** [comment]
Glad that it solved the problem, although not practical. This is indeed one weird issue.

One last request if I may:
Can you use your Premium account and open a playlist to a queue + get the resulting JSON from [http://localhost:26538/api/v1/queue](http://localhost:26538/api/v1/queue)?

If the queue on YouTube Music Remote is incomplete and the JSON from the API is also incomplete, this issue can be raised to YouTube Music directly.

**Comment by Dzheremi2** [comment]
> One last request if I may: Can you use your Premium account and open a playlist to a queue + get the resulting JSON from http://localhost:26538/api/v1/queue (and possibly send the playlist/album + JSON here)?

Queue of the same playlist (There Goes the Neighborhood)
[queue.json](https://github.com/user-attachments/files/18269278/queue.json)

**Comment by franz-dc** [comment]
Thanks for sending the JSON!
It seems that albums that have a song-only counterpart has a different JSON schema, breaking some filtering logic in the queue.

I'll be making a fix regarding this later.
